
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate-db
  labels:
    app: weaviate
    project: aviata-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - name: weaviate-db
        image: semitechnologies/weaviate:1.23.9
        ports:
        - containerPort: 8080
        - containerPort: 50051
        env:
        - name: OPENAI_KEY
          valueFrom: 
            secretKeyRef:
              name: openai
              key: openai-key
        - name: QUERY_DEFAULTS_LIMIT
          value: "25"
        - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
          value: "true"
        - name: PERSISTENCE_DATA_PATH
          value: "/var/lib/weaviate"
        - name: DEFAULT_VECTORIZER_MODULE
          value: "text2vec-openai"
        - name: ENABLE_MODULES
          value: "text2vec-openai,generative-openai"
        - name: CLUSTER_HOSTNAME
          value: "node1"
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate
spec:
  selector:
    app: weaviate
  type: LoadBalancer # For testing only
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  # ports:
  #   - protocol: TCP
  #     port: 50051
  #     targetPort: 50051